# Generated by Django 4.2.4 on 2023-08-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateField(default='2000-12-12', verbose_name='дата создания'),
        ),
    ]
