# Generated by Django 4.2.4 on 2023-09-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='flag',
            field=models.BooleanField(default=False, verbose_name='признак текущей версии'),
        ),
    ]
