# Generated by Django 4.2.4 on 2023-09-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_version_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='flag',
            field=models.BooleanField(default=True, verbose_name='признак текущей версии'),
        ),
    ]
